In [1]:
import numpy as np
import random
import pandas as pd
import sys
import networkx as nx
import matplotlib.pyplot as plt
import math as mt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection
a = sys.path.append('../modules/')  # endereco das funcoes implementadas por voce!
import sphere, sample_random, aux_operators_array, Operators_array, plot_3D

In [2]:
population = {'xmax': 5000.0,
                'xmin': -5000.0,
                'ymax': 5000.0,
                'ymin': -5000.0,
                'zlim': 7000.0,
                'z_min': 0.0,
                'n_dip': 4,
                'n_pop': 2,
                'inclmax': 5.0,
                'inclmin': -5.0,
                'declmax': 5.0,
                'declmin': -5.0,
                'magmax': 2.5,
                'magmin': 1.5,
                'homogeneo': True
                }


filhos_mut = {'xmax': 5000.0,
                'xmin': -5000.0,
                'ymax': 5000.0,
                'ymin': -5000.0,
                'zlim': 7000.0,
                'z_min': 0.0,
                'n': 1,
                'inclmax': 5.0,
                'inclmin': -5.0,
                'declmax': 5.0,
                'declmin': -5.0,
                'magmax': 2.5,
                'magmin': 1.5,
                'homogeneo': True
                }

In [3]:
populacao = Operators_array.create_population(**population)

In [4]:
print(populacao[0])
print(populacao[0][0])

[[-7.14773824e+02  1.03677194e+03  3.57922919e+02]
 [ 1.37987972e+03 -4.56503246e+03  3.63375117e+03]
 [-2.03055582e+02  4.60171423e+02  7.18975035e+02]
 [ 2.01543176e+03 -3.78502796e+03  4.32999589e+03]
 [ 4.94100420e+00 -1.09855348e+00  1.69589451e+00]]
[-714.77382361 1036.77194408  357.92291875]


In [5]:
def mutacao_multi_vhomo(filho, xmax, xmin, ymax, ymin, zlim, z_min, inclmax, inclmin, declmax, declmin, magmax, magmin, n, homogeneo):

    prob_mut = 0.05
    n_dip = len(filho[0]) - 1
    n_param = 6
    for index, rand_mut in enumerate(filho): #Index = qual será o indivíduo que será mutado.
        rand_mut = random.random()
        if prob_mut > rand_mut:
            dip_select = random.sample(range(0,(len(filho[0]) - 2)), k=(int(n_dip/2))) #Seleção qual dipolo será mutado.
            param_select = random.sample(range(0, (len(populacao[0][0]) + 3)), k=(int(n_param/2))) #Selecão qual parâmetro será mutado.
            for round in dip_select:
                for param in param_select:
                    if param <= 2:
                        coodX, coodY, coodZ = sample_random.sample_random_coordinated(xmax, xmin, ymax, ymin, zlim, z_min, n)
                    if param == 0:
                        filho[index][round][param] = coodX[0]
                    elif param == 1:
                        filho[index][round][param] = coodY[0]
                    elif param == 2:
                        filho[index][round][param] = coodZ[0]
                    else:
                        incl, decl, mag = sample_random.sample_random_mag(inclmax, inclmin, declmax, declmin, magmax, magmin, n, homogeneo)
                    if param == 3:
                        filho[index][len(filho[0])-1][0] = incl[0]
                    elif param == 4:
                        filho[index][len(filho[0])-1][1] = decl[0]
                    elif param == 5:
                        filho[index][len(filho[0])-1][2] = mag[0]

    return filho

In [6]:
n_dip = 4
bb = len(populacao[0]) - 1
print(bb)
n_param = 6
dipol_select = random.sample(range(0,(len(populacao[0]) - 2)), k=(int(n_dip/2)))
param_select = random.sample(range(0, (len(populacao[0][0]) + 3)), k=(int(n_param/2)))
print(dipol_select)
print(param_select)

4
[2, 1]
[2, 5, 0]


In [7]:
print(populacao)

[array([[-7.14773824e+02,  1.03677194e+03,  3.57922919e+02],
       [ 1.37987972e+03, -4.56503246e+03,  3.63375117e+03],
       [-2.03055582e+02,  4.60171423e+02,  7.18975035e+02],
       [ 2.01543176e+03, -3.78502796e+03,  4.32999589e+03],
       [ 4.94100420e+00, -1.09855348e+00,  1.69589451e+00]]), array([[ 3.95553097e+03, -2.64640659e+03,  1.85579342e+03],
       [ 1.52365867e+03, -1.10213387e+03,  2.42435319e+03],
       [-7.93759337e+01,  2.97840058e+03,  4.98469324e+03],
       [ 3.05297055e+03,  3.69991984e+03,  6.83298435e+03],
       [ 3.29135307e+00,  5.66380840e-01,  1.97684581e+00]])]


In [8]:
mut_ = mutacao_multi_vhomo(populacao,**filhos_mut)

In [9]:
print(mut_)

[array([[-7.14773824e+02,  1.03677194e+03,  3.57922919e+02],
       [ 1.37987972e+03, -4.56503246e+03,  3.63375117e+03],
       [-2.03055582e+02,  4.60171423e+02,  7.18975035e+02],
       [ 2.01543176e+03, -3.78502796e+03,  4.32999589e+03],
       [ 4.94100420e+00, -1.09855348e+00,  1.69589451e+00]]), array([[ 3.95553097e+03, -2.64640659e+03,  1.85579342e+03],
       [ 1.52365867e+03, -1.10213387e+03,  2.42435319e+03],
       [-7.93759337e+01,  2.97840058e+03,  4.98469324e+03],
       [ 3.05297055e+03,  3.69991984e+03,  6.83298435e+03],
       [ 3.29135307e+00,  5.66380840e-01,  1.97684581e+00]])]


In [29]:
vetor_test = [5,5,5,5,5,5,2,2,2,3,7,7,7,7,7]
vv = vetor_test[0:15:5]
print(len(vetor_test))
print(vv)

15
[5, 5, 7]


In [30]:
for i in range(len(vetor_test)):
    if (i % 5 == 0) and (vetor_test[i] == vetor_test[i-5]):
        print('aumenta mut para 0,2')
    else:
        print("mantem em 0,05")
        

mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
aumenta mut para 0,2
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
mantem em 0,05
