In [1]:
import numpy as np
import random
import pandas as pd
import sys
import networkx as nx
import matplotlib.pyplot as plt
import math as mt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Poly3DCollection, Line3DCollection
a = sys.path.append('../modules/')  # endereco das funcoes implementadas por voce!
import sphere, sample_random, aux_operators_array, Operators_array, plot_3D

In [2]:
population = {'xmax': 5000.0,
                'xmin': -5000.0,
                'ymax': 5000.0,
                'ymin': -5000.0,
                'zlim': 7000.0,
                'z_min': 0.0,
                'n_dip': 4,
                'n_pop': 2,
                'inclmax': 5.0,
                'inclmin': -5.0,
                'declmax': 5.0,
                'declmin': -5.0,
                'magmax': 2.5,
                'magmin': 1.5,
                'homogeneo': True
                }


filhos_mut = {'xmax': 5000.0,
                'xmin': -5000.0,
                'ymax': 5000.0,
                'ymin': -5000.0,
                'zlim': 7000.0,
                'z_min': 0.0,
                'n': 1,
                'inclmax': 5.0,
                'inclmin': -5.0,
                'declmax': 5.0,
                'declmin': -5.0,
                'magmax': 2.5,
                'magmin': 1.5,
                'homogeneo': True
                }

In [3]:
populacao = Operators_array.create_population(**population)

In [4]:
print(populacao[0])
print(populacao[0][0])

[[-4.95225813e+03 -1.78771942e+03  1.35753096e+03]
 [-6.73312742e+02 -1.13317055e+03  6.86971159e+03]
 [-1.62640934e+03  1.51354729e+03  6.91143773e+03]
 [-1.82576982e+03  5.47835820e+02  3.69308586e+03]
 [ 3.93669568e+00 -4.79859331e+00  2.34536913e+00]]
[-4952.25812809 -1787.71941885  1357.53095972]


In [5]:
def mutacao_multi_vhomo(filho, xmax, xmin, ymax, ymin, zlim, z_min, inclmax, inclmin, declmax, declmin, magmax, magmin, n, homogeneo):

    prob_mut = 0.05
    n_dip = len(filho[0]) - 1
    n_param = 6
    for index, rand_mut in enumerate(filho): #Index = qual será o indivíduo que será mutado.
        rand_mut = random.random()
        if prob_mut > rand_mut:
            dip_select = random.sample(range(0,(len(filho[0]) - 2)), k=(int(n_dip/2))) #Seleção qual dipolo será mutado.
            param_select = random.sample(range(0, (len(populacao[0][0]) + 3)), k=(int(n_param/2))) #Selecão qual parâmetro será mutado.
            for round in dip_select:
                for param in param_select:
                    if param <= 2:
                        coodX, coodY, coodZ = sample_random.sample_random_coordinated(xmax, xmin, ymax, ymin, zlim, z_min, n)
                    if param == 0:
                        filho[index][round][param] = coodX[0]
                    elif param == 1:
                        filho[index][round][param] = coodY[0]
                    elif param == 2:
                        filho[index][round][param] = coodZ[0]
                    else:
                        incl, decl, mag = sample_random.sample_random_mag(inclmax, inclmin, declmax, declmin, magmax, magmin, n, homogeneo)
                    if param == 3:
                        filho[index][len(filho[0])-1][0] = incl[0]
                    elif param == 4:
                        filho[index][len(filho[0])-1][1] = decl[0]
                    elif param == 5:
                        filho[index][len(filho[0])-1][2] = mag[0]

    return filho

In [6]:
n_dip = 4
bb = len(populacao[0]) - 1
print(bb)
n_param = 6
dipol_select = random.sample(range(0,(len(populacao[0]) - 2)), k=(int(n_dip/2)))
param_select = random.sample(range(0, (len(populacao[0][0]) + 3)), k=(int(n_param/2)))
print(dipol_select)
print(param_select)

4
[2, 0]
[3, 0, 4]


In [7]:
print(populacao)

[array([[-4.95225813e+03, -1.78771942e+03,  1.35753096e+03],
       [-6.73312742e+02, -1.13317055e+03,  6.86971159e+03],
       [-1.62640934e+03,  1.51354729e+03,  6.91143773e+03],
       [-1.82576982e+03,  5.47835820e+02,  3.69308586e+03],
       [ 3.93669568e+00, -4.79859331e+00,  2.34536913e+00]]), array([[-1.99157338e+03, -3.45868328e+03,  5.60998691e+03],
       [-3.04040647e+03,  3.63276524e+03,  2.35316249e+03],
       [ 6.78020697e+02,  3.43294100e+03,  2.99076680e+02],
       [ 2.09058773e+03, -3.82326472e+03,  3.65650624e+03],
       [-3.42703776e+00, -1.84290518e+00,  1.86475224e+00]])]


In [10]:
mut_ = mutacao_multi_vhomo(populacao,**filhos_mut)

In [11]:
print(mut_)

[array([[-4.95225813e+03, -1.78771942e+03,  1.35753096e+03],
       [-6.73312742e+02, -1.13317055e+03,  6.86971159e+03],
       [-1.62640934e+03,  1.51354729e+03,  6.91143773e+03],
       [-1.82576982e+03,  5.47835820e+02,  3.69308586e+03],
       [ 3.93669568e+00, -4.79859331e+00,  2.34536913e+00]]), array([[-1.99157338e+03, -3.45868328e+03,  5.60998691e+03],
       [-3.04040647e+03,  3.63276524e+03,  2.35316249e+03],
       [ 6.78020697e+02,  3.43294100e+03,  2.99076680e+02],
       [ 2.09058773e+03, -3.82326472e+03,  3.65650624e+03],
       [-3.42703776e+00, -1.84290518e+00,  1.86475224e+00]])]
